services:
  web-stg:
    image: ghcr.io/yk-graph/air-booking-web:staging
    container_name: air-booking-web-stg
    ports:
      - '4210:4000'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
